### ISSUE TITLE
peewee.OperationalError: table history has no column named vidID

### ISSUE THREAD

**Issue by lesgrossman** [JasonMillward/Autorippr#110]
Just sync'd the latest code, merge the settings.cfg received the following 

Traceback (most recent call last):
  File "./autorippr.py", line 391, in <module>
    rip(config)
  File "./autorippr.py", line 166, in rip
    "Video added to database"
  File "/home/choman/Autorippr/classes/database.py", line 140, in insert_history
    historytypeid=typeid
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3755, in create
    inst.save(force_insert=True)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3890, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2685, in execute
    return self.database.last_insert_id(self._execute(), self.model_class)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2243, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2877, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2732, in __exit__
    reraise(new_type, new_type(*exc_value.args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2869, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: table history has no column named vidID

**Comment by JasonMillward** [comment]
Have you deleted the old database and let it be recreated? 

I haven't figured out how to put in database migrations yet so this step is required for some updates.

**Comment by lesgrossman** [comment]
That was it, removing the DB worked
