### ISSUE TITLE
Error running latest Autorippr

### ISSUE THREAD

**Issue by formeroosid** [JasonMillward/Autorippr#137]
I get the following when I try to run the script. 

Output from command python /usr/local/bin/Autorippr/autorippr.py --rip --compress --silent ..
Traceback (most recent call last):
  File "/usr/local/bin/Autorippr/autorippr.py", line 62, in <module>
    from classes import *
  File "/usr/local/bin/Autorippr/classes/mediainfo.py", line 25, in <module>
    from pymediainfo import MediaInfo
ImportError: No module named pymediainfo

Any help would be appreciated. 

Jamie

**Comment by formeroosid** [comment]
Nevermind. I reinstalled the pymediainfo Python Module and life is good. 

sudo pip install pymediainfo
