### ISSUE TITLE
Movie exceeds maxLength

### ISSUE THREAD

**Issue by nickrupert7** [JasonMillward/Autorippr#138]
Hi Jason,
I'm getting this weird error where a movie blu-ray won't rip because the title exceeds the maxLength. I've never had this happen before, and I haven't changed my preferences in `settings.cfg`. Here's the exact debug log:
```
2017-05-07 11:08:49 - Rip - DEBUG - Ripping initialised
2017-05-07 11:08:49 - Rip - DEBUG - Checking for DVDs
2017-05-07 11:08:51 - Rip - DEBUG - 1 DVD(s) found
2017-05-07 11:09:28 - Makemkv - DEBUG - MakeMKV found 2 titles
2017-05-07 11:09:28 - Makemkv - DEBUG - Excluding Title No.: 1, Title: ['Iron_Man_2_Disc_1_t01.mkv']. Exceeds maxLength
2017-05-07 11:09:28 - Makemkv - DEBUG - Excluding Title No.: 0, Title: ['Iron_Man_2_Disc_1_t00.mkv']. Exceeds maxLength
2017-05-07 11:09:28 - Rip - INFO - No video titles found
2017-05-07 11:09:28 - Rip - INFO - Try decreasing 'minLength' in the config and try again
2017-05-07 11:09:28 - Compress - DEBUG - Compressing initialised
2017-05-07 11:09:28 - Compress - DEBUG - Looking for videos to compress
2017-05-07 11:09:28 - Compress - INFO - Queue does not exist or is empty
```
Now, I thought (according to the comment in settings.cfg) that maxLength was only used for TV shows?

More info you might need to know:
I was unfortunately forced to reinstall the OS (Ubuntu) on my server, but I was able to directly copy everything relating to Autorippr over before the reinstall. This is my first use of Autorippr since the reinstall.
I have reinstalled MakeMKV and confirmed that it is working with the key I purchased.

When I do increase the maxLength (although it shouldn't make a difference, since this is a movie), I get another error:
```
2017-05-07 11:40:34 - Rip - DEBUG - Ripping initialised
2017-05-07 11:40:34 - Rip - DEBUG - Checking for DVDs
2017-05-07 11:40:42 - Rip - DEBUG - 1 DVD(s) found
2017-05-07 11:41:15 - Makemkv - DEBUG - MakeMKV found 2 titles
2017-05-07 11:41:15 - Makemkv - DEBUG - MakeMKV title info: Disc Title: ['Iron Man 2 Disc 1'], Title No.: 1, Title: ['Iron_Man_2_Disc_1_t01.mkv'], 
2017-05-07 11:41:15 - Makemkv - DEBUG - MakeMKV title info: Disc Title: ['Iron Man 2 Disc 1'], Title No.: 0, Title: ['Iron_Man_2_Disc_1_t00.mkv'], 
Traceback (most recent call last):
  File "/home/nick/Applications/Autorippr/autorippr.py", line 391, in <module>
    rip(config)
  File "/home/nick/Applications/Autorippr/autorippr.py", line 161, in rip
    filebot
  File "/home/nick/Applications/Autorippr/classes/database.py", line 153, in insert_video
    lastupdated=datetime.now()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4905, in create
    inst.save(force_insert=True)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 5098, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3516, in execute
    cursor = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2902, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3765, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3588, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3758, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: unable to open database file
```
Thanks

Update: I tried another movie, and I don't get the exceeds maxLength issue, but I do get the other crash/traceback.

**Comment by carrigan98** [comment]
It's because the python regex finds Disc_1 in the title and assumes it's a TV series. To overcome this, use --force_db=movie.

**Comment by nickrupert7** [comment]
Great! I'll look at that. Any word on the other error that's happening regardless? Something wrong with peewee? I tried updating peewee using pip, but the error still persists

Thanks!

**Comment by JasonMillward** [comment]
`unable to open database file` 

I would say it's either a permissions issue or the file doesn't exist.

**Comment by nickrupert7** [comment]
Deleted and re-cloned Autorippr. Appears to be working now, so I guess it was some kind of weird issue in the migration process.
Thanks!
