### ISSUE TITLE
makeMKV never starts

### ISSUE THREAD

**Issue by cyberhiker** [JasonMillward/Autorippr#69]
This is a clean, new install of a headless Ubuntu 14.04 instance with the --test running successfully.  I am using makeMKV version 1.9.1 and I am getting the following error from the debug output:  

    2015-02-19 14:36:26 - Rip - DEBUG - Ripping initialised
    2015-02-19 14:36:26 - Rip - DEBUG - Checking for DVDs
    2015-02-19 14:36:30 - Rip - DEBUG - 1 DVDs found
    2015-02-19 14:36:46 - Makemkv - DEBUG - MakeMKV found 1 titles
    Traceback (most recent call last):
      File "autorippr.py", line 317, in <module>
        rip(config)
      File "autorippr.py", line 155, in rip
        database.update_movie(dbMovie, 3, mkv_api.get_savefile())
      File "/home/chris/Autorippr/classes/makemkv.py", line 298, in get_savefile
        return self.saveFile
    AttributeError: 'makeMKV' object has no attribute 'saveFile'

MakeMKVcon seems to run fine when I do `makemkvcon info disk:0` but I don't know enough to provide anymore with out guidance.

Let me know if you need something else to help track this down further.

**Comment by JasonMillward** [comment]
Intresting, it looks like it's not reaching [line 289](https://github.com/JasonMillward/Autorippr/blob/master/classes/makemkv.py#L289).

What branch are you using? If you're using `1.6` can you check `master` and try again?

**Comment by cyberhiker** [comment]
I'm on the 1.6 master.

**Comment by JasonMillward** [comment]
You can't be on both, you're either on `v1.6` or on `master`. 

What does `git branch` tell you?

**Comment by tjordan170** [comment]
I'm having the same problem. Any thoughts?
>git branch
* (detached from v1.6)
  master

**Comment by JasonMillward** [comment]
Hmm, git seems to be confusing the issue slightly. 

See if you can switch to the proper master 

`git checkout master`

Then run git branch again, it should look something like this:

    $ git branch
    * master

**Comment by cyberhiker** [comment]
Same. I'm on master and did a pull. Same issue. 




I can give you SSH access to my box for you to debug. 




-C

**Comment by JasonMillward** [comment]
I'd rather not have access to your box right now. 

Let me make some changes first, and if all else fails I'll take you up on your offer.

**Comment by cyberhiker** [comment]
What's the word?  Need any help with anything?

**Comment by JasonMillward** [comment]
My appologies, some family matters distracted me. 

Can you please checkout branch [issue-69](https://github.com/JasonMillward/Autorippr/tree/issue-69) and run using `python autorippr.py --debug --rip`

There are some new debug options and I'm interested in this part;

    2015-03-06 11:07:36 - Makemkv - DEBUG - MakeMKV found 1 titles
    2015-03-06 11:07:36 - Makemkv - DEBUG - Title number: 0
    2015-03-06 11:07:36 - Makemkv - DEBUG - ['Totally a movie']
    2015-03-06 11:07:36 - Makemkv - DEBUG - MakeMKV title info: ['title00.mkv']
    2015-03-06 11:07:36 - Makemkv - DEBUG - saveFile returned: 'title00.mkv'

**Comment by cyberhiker** [comment]
Here you go:

    2015-03-05 21:16:52 - Rip - DEBUG - Ripping initialised
    2015-03-05 21:16:52 - Rip - DEBUG - Checking for DVDs
    2015-03-05 21:16:57 - Rip - DEBUG - 1 DVDs found
    2015-03-05 21:17:13 - Makemkv - DEBUG - MakeMKV found 1 titles
    2015-03-05 21:17:13 - Makemkv - DEBUG - saveFile returned: ''
    2015-03-05 21:17:29 - Makemkv - ERROR - MakeMKV (rip_disc) returned status code: 11
    2015-03-05 21:17:29 - Makemkv - ERROR - Profile parsing error: default profile missing, using builtin default
    2015-03-05 21:17:29 - Rip - INFO - MakeMKV did not did not complete successfully
    2015-03-05 21:17:29 - Rip - INFO - See log for more details
    2015-03-05 21:17:29 - Rip - DEBUG - Movie title: Rock And Roll

**Comment by JasonMillward** [comment]
Okay, your disc doesn't seem to be showing any TINFO messages.

What output do you get when you run `grep "TINFO" /tmp/makemkvMessages` ?

**Comment by cyberhiker** [comment]
Nothing.  No output.  Tried it with and without quotes.

**Comment by JasonMillward** [comment]
This is strange, MakeMKV is not returning any title info from your disc, but it thinks it finds 1 title.

What do these give? 

`grep "added" /tmp/makemkvMessages`

`grep "TCOUNT" /tmp/makemkvMessages`

**Comment by cyberhiker** [comment]
~$ grep "added" /tmp/makemkvMessages
    ~$ grep "TCOUNT" /tmp/makemkvMessages
TCOUNT:0

**Comment by JasonMillward** [comment]
Fantastic! I have found the issue and should have a fix shortly.

**Comment by JasonMillward** [comment]
Can you pull the changes from [issue-69](https://github.com/JasonMillward/Autorippr/tree/issue-69) and run again using `python autorippr.py --debug --rip`

If I found the right issue, it should not crash any more and instead return a nice message.

**Comment by cyberhiker** [comment]
Excellent.  It is all working now!
