### ISSUE TITLE
Error when running cron job

### ISSUE THREAD

**Issue by formeroosid** [JasonMillward/Autorippr#83]
I've setup my cron job but ripping doesn't succeed. I've set the debug option and I get this:

2015-07-15 07:37:01 - Rip - DEBUG - Ripping initialised
2015-07-15 07:37:01 - Rip - DEBUG - Checking for DVDs
2015-07-15 07:37:07 - Rip - DEBUG - 1 DVDs found
2015-07-15 07:37:19 - Makemkv - DEBUG - MakeMKV found 4 titles
2015-07-15 07:37:19 - Makemkv - DEBUG - MakeMKV title info: Disc Title: ['Game Of Thrones Season 3 Disc 2'], Title No.: 1, Title: ['Game_Of_Thrones_Season_3_Disc_2_t01.mkv'], 
2015-07-15 07:37:19 - Makemkv - DEBUG - MakeMKV title info: Disc Title: ['Game Of Thrones Season 3 Disc 2'], Title No.: 0, Title: ['Game_Of_Thrones_Season_3_Disc_2_t00.mkv'], 
2015-07-15 07:37:19 - Makemkv - DEBUG - MakeMKV title info: Disc Title: ['Game Of Thrones Season 3 Disc 2'], Title No.: 3, Title: ['Game_Of_Thrones_Season_3_Disc_2_t03.mkv'], 
2015-07-15 07:37:19 - Makemkv - DEBUG - MakeMKV title info: Disc Title: ['Game Of Thrones Season 3 Disc 2'], Title No.: 2, Title: ['Game_Of_Thrones_Season_3_Disc_2_t02.mkv'], 
Traceback (most recent call last):
  File "/usr/local/bin/Autorippr/autorippr.py", line 357, in <module>
    rip(config)
  File "/usr/local/bin/Autorippr/autorippr.py", line 160, in rip
    forceDisableFB
  File "/usr/local/bin/Autorippr/classes/database.py", line 145, in insert_movie
    lastupdated=datetime.now()
  File "build/bdist.linux-x86_64/egg/peewee.py", line 3868, in create
  File "build/bdist.linux-x86_64/egg/peewee.py", line 4004, in save
  File "build/bdist.linux-x86_64/egg/peewee.py", line 2748, in execute
  File "build/bdist.linux-x86_64/egg/peewee.py", line 2300, in _execute
  File "build/bdist.linux-x86_64/egg/peewee.py", line 2960, in execute_sql
  File "build/bdist.linux-x86_64/egg/peewee.py", line 2810, in __exit__
  File "build/bdist.linux-x86_64/egg/peewee.py", line 2952, in execute_sql
peewee.OperationalError: table movies has no column named multititle

Any thoughts?

Jamie

**Comment by ascendedguard** [comment]
Looks like you updated from test1 to test2. You need to delete `autorippr.sqlite` as the database schema updated.

See: https://github.com/JasonMillward/Autorippr/issues/80

**Comment by formeroosid** [comment]
Perfect. Working now. Thanks!
